name: web_cookies
description: A cookie manager for http requests in Dart, by which you can deal with the complex cookie policy and persist cookies easily.
version: 2.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.16.2
  pedantic: ^1.10.0
#  coverage: "^0.12.4"
#  dart_codecov_generator:
#    git:
#      url: "https://github.com/wendux/dart-codecov.git"
